version: 0.1
phases:
        pre_build:
                commands:
                        - npm install
                        - cp config/api.js node_modules/jsdom/lib/api.js
                        - cp config/defaults.js node_modules/jest-config/build/defaults.js
                        - cp config/valid_config.js node_modules/jest-config/build/valid_config.js
                        - npm test
        build:
                commands:
                        - npm install
                        - npm run webpack
artifacts:
        files:
                - index.html
                - react.html
                - babel.html
                - favicon.ico
                - styles/*
                - images/*
                - dist/bundle.js
