version: 0.1
phases:
        build:
                commands:
                        - npm install webpack
                        - npm run webpack
artifacts:
        files:
                - index.html
                - react.html
                - babel.html
                - favicon.ico
                - styles/*
                - images/*
                - dist/bundle.js
