version: 0.1
phases:
        build:
                commands:
                        - echo Nothing to do Yet
artifacts:
        files:
                - index.html
                - react.html
                - babel.html
                - favicon.ico
                - styles/*
                - images/*
