version: 0.1
phases:
        build:
                commands:
                        - echo Nothing to do Yet
artifacts:
        files:
                - *.html
                - favicon.ico
                - styles/*
                - images/*
