version:0.1
phases:
        build:
                commands:
                        - echo Nothing to do Yet
        artifacts:
                - index.html
                - favicon.ico
                - styles/*
                - images/*
